spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/shopsense_db
spring.datasource.username=shopsense_user
spring.datasource.password=shopsense_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=shopsense-development-secret-key-change-this-later-123456
jwt.expiration-ms=86400000

ollama.url=http://localhost:11434/api/generate
ollama.model=llama3.2:3b
ollama.embedding-url=http://localhost:11434/api/embeddings
ollama.embedding-model=nomic-embed-text